server:
  port: 9001
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: media-catalog-service
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/db_media_catalog
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false # makes a failure to connect to the config server fatal
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Zakytok
management:
  endpoints:
    web:
      exposure:
        include: '*'

zakytok:
  greeting: "Welcome to the local catalog!"